// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/go-kratos/kratos/v2/log"
	"github.com/kwstars/film-hive/app/rating/service/internal/biz"
	"github.com/kwstars/film-hive/app/rating/service/internal/conf"
	"github.com/kwstars/film-hive/app/rating/service/internal/data"
)

// Injectors from wire.go:

func createRatingService(bootstrap *conf.Bootstrap, log2 log.Logger) (*RatingService, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, log2)
	if err != nil {
		return nil, nil, err
	}
	ratingRepo := data.NewRatingRepo(dataData, log2)
	ratingUsecase := biz.NewRatingUsecase(ratingRepo, log2)
	ratingService := NewRatingService(ratingUsecase)
	return ratingService, func() {
		cleanup()
	}, nil
}
