apiVersion: v1
kind: Secret # 定义 Kubernetes 中的资源类型为 Secret
metadata:
  name: mysecret # Secret 的名称，可以根据实际情况更改
type: Opaque # 指定该 Secret 存储的数据不需要进行编码或加密
data:
  username: dXNlcm5hbWU= # 存储用户名信息的 Base64 编码值
  password: cGFzc3dvcmQ= # 存储密码信息的 Base64 编码值
stringData:
  key: value # 可以直接存储字符串类型的数据
