// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.1
// - protoc             v3.12.4
// source: movie/service/v1/movie.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMovieServiceGetMovieDetail = "/movie.service.v1.MovieService/GetMovieDetail"

type MovieServiceHTTPServer interface {
	GetMovieDetail(context.Context, *GetMovieDetailRequest) (*GetMovieDetailResponse, error)
}

func RegisterMovieServiceHTTPServer(s *http.Server, srv MovieServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/movie/{id}", _MovieService_GetMovieDetail0_HTTP_Handler(srv))
}

func _MovieService_GetMovieDetail0_HTTP_Handler(srv MovieServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMovieDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMovieServiceGetMovieDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMovieDetail(ctx, req.(*GetMovieDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMovieDetailResponse)
		return ctx.Result(200, reply)
	}
}

type MovieServiceHTTPClient interface {
	GetMovieDetail(ctx context.Context, req *GetMovieDetailRequest, opts ...http.CallOption) (rsp *GetMovieDetailResponse, err error)
}

type MovieServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMovieServiceHTTPClient(client *http.Client) MovieServiceHTTPClient {
	return &MovieServiceHTTPClientImpl{client}
}

func (c *MovieServiceHTTPClientImpl) GetMovieDetail(ctx context.Context, in *GetMovieDetailRequest, opts ...http.CallOption) (*GetMovieDetailResponse, error) {
	var out GetMovieDetailResponse
	pattern := "/movie/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMovieServiceGetMovieDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
