// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.12.4
// source: movie/service/v1/movie.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMovieDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMovieDetailRequest) Reset() {
	*x = GetMovieDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_service_v1_movie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieDetailRequest) ProtoMessage() {}

func (x *GetMovieDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_v1_movie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieDetailRequest.ProtoReflect.Descriptor instead.
func (*GetMovieDetailRequest) Descriptor() ([]byte, []int) {
	return file_movie_service_v1_movie_proto_rawDescGZIP(), []int{0}
}

func (x *GetMovieDetailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMovieDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rating   float64                          `protobuf:"fixed64,1,opt,name=rating,proto3" json:"rating,omitempty"`
	Metadata *GetMovieDetailResponse_Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *GetMovieDetailResponse) Reset() {
	*x = GetMovieDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_service_v1_movie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieDetailResponse) ProtoMessage() {}

func (x *GetMovieDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_v1_movie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieDetailResponse.ProtoReflect.Descriptor instead.
func (*GetMovieDetailResponse) Descriptor() ([]byte, []int) {
	return file_movie_service_v1_movie_proto_rawDescGZIP(), []int{1}
}

func (x *GetMovieDetailResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GetMovieDetailResponse) GetMetadata() *GetMovieDetailResponse_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetMovieDetailResponse_Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Director    string `protobuf:"bytes,4,opt,name=director,proto3" json:"director,omitempty"`
}

func (x *GetMovieDetailResponse_Metadata) Reset() {
	*x = GetMovieDetailResponse_Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_service_v1_movie_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieDetailResponse_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieDetailResponse_Metadata) ProtoMessage() {}

func (x *GetMovieDetailResponse_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_movie_service_v1_movie_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieDetailResponse_Metadata.ProtoReflect.Descriptor instead.
func (*GetMovieDetailResponse_Metadata) Descriptor() ([]byte, []int) {
	return file_movie_service_v1_movie_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetMovieDetailResponse_Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMovieDetailResponse_Metadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetMovieDetailResponse_Metadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetMovieDetailResponse_Metadata) GetDirector() string {
	if x != nil {
		return x.Director
	}
	return ""
}

var File_movie_service_v1_movie_proto protoreflect.FileDescriptor

var file_movie_service_v1_movie_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xef, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x4d, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x6e, 0x0a, 0x08, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x83, 0x01, 0x0a, 0x0c, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x27, 0x2e, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x0e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x08, 0x12, 0x06, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x42,
	0x19, 0x5a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_movie_service_v1_movie_proto_rawDescOnce sync.Once
	file_movie_service_v1_movie_proto_rawDescData = file_movie_service_v1_movie_proto_rawDesc
)

func file_movie_service_v1_movie_proto_rawDescGZIP() []byte {
	file_movie_service_v1_movie_proto_rawDescOnce.Do(func() {
		file_movie_service_v1_movie_proto_rawDescData = protoimpl.X.CompressGZIP(file_movie_service_v1_movie_proto_rawDescData)
	})
	return file_movie_service_v1_movie_proto_rawDescData
}

var file_movie_service_v1_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_movie_service_v1_movie_proto_goTypes = []interface{}{
	(*GetMovieDetailRequest)(nil),           // 0: movie.service.v1.GetMovieDetailRequest
	(*GetMovieDetailResponse)(nil),          // 1: movie.service.v1.GetMovieDetailResponse
	(*GetMovieDetailResponse_Metadata)(nil), // 2: movie.service.v1.GetMovieDetailResponse.Metadata
}
var file_movie_service_v1_movie_proto_depIdxs = []int32{
	2, // 0: movie.service.v1.GetMovieDetailResponse.metadata:type_name -> movie.service.v1.GetMovieDetailResponse.Metadata
	0, // 1: movie.service.v1.MovieService.GetMovieDetail:input_type -> movie.service.v1.GetMovieDetailRequest
	1, // 2: movie.service.v1.MovieService.GetMovieDetail:output_type -> movie.service.v1.GetMovieDetailResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_movie_service_v1_movie_proto_init() }
func file_movie_service_v1_movie_proto_init() {
	if File_movie_service_v1_movie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_movie_service_v1_movie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_service_v1_movie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_service_v1_movie_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieDetailResponse_Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_movie_service_v1_movie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_service_v1_movie_proto_goTypes,
		DependencyIndexes: file_movie_service_v1_movie_proto_depIdxs,
		MessageInfos:      file_movie_service_v1_movie_proto_msgTypes,
	}.Build()
	File_movie_service_v1_movie_proto = out.File
	file_movie_service_v1_movie_proto_rawDesc = nil
	file_movie_service_v1_movie_proto_goTypes = nil
	file_movie_service_v1_movie_proto_depIdxs = nil
}
