// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: movie/service/v1/movie.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetMovieDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMovieDetailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMovieDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMovieDetailRequestMultiError, or nil if none found.
func (m *GetMovieDetailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMovieDetailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetMovieDetailRequestMultiError(errors)
	}

	return nil
}

// GetMovieDetailRequestMultiError is an error wrapping multiple validation
// errors returned by GetMovieDetailRequest.ValidateAll() if the designated
// constraints aren't met.
type GetMovieDetailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMovieDetailRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMovieDetailRequestMultiError) AllErrors() []error { return m }

// GetMovieDetailRequestValidationError is the validation error returned by
// GetMovieDetailRequest.Validate if the designated constraints aren't met.
type GetMovieDetailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMovieDetailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMovieDetailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMovieDetailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMovieDetailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMovieDetailRequestValidationError) ErrorName() string {
	return "GetMovieDetailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetMovieDetailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMovieDetailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMovieDetailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMovieDetailRequestValidationError{}

// Validate checks the field values on GetMovieDetailResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMovieDetailResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMovieDetailResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMovieDetailResponseMultiError, or nil if none found.
func (m *GetMovieDetailResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMovieDetailResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Rating

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMovieDetailResponseValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMovieDetailResponseValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMovieDetailResponseValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetMovieDetailResponseMultiError(errors)
	}

	return nil
}

// GetMovieDetailResponseMultiError is an error wrapping multiple validation
// errors returned by GetMovieDetailResponse.ValidateAll() if the designated
// constraints aren't met.
type GetMovieDetailResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMovieDetailResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMovieDetailResponseMultiError) AllErrors() []error { return m }

// GetMovieDetailResponseValidationError is the validation error returned by
// GetMovieDetailResponse.Validate if the designated constraints aren't met.
type GetMovieDetailResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMovieDetailResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMovieDetailResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMovieDetailResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMovieDetailResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMovieDetailResponseValidationError) ErrorName() string {
	return "GetMovieDetailResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetMovieDetailResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMovieDetailResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMovieDetailResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMovieDetailResponseValidationError{}

// Validate checks the field values on GetMovieDetailResponse_Metadata with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMovieDetailResponse_Metadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMovieDetailResponse_Metadata with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetMovieDetailResponse_MetadataMultiError, or nil if none found.
func (m *GetMovieDetailResponse_Metadata) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMovieDetailResponse_Metadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for Director

	if len(errors) > 0 {
		return GetMovieDetailResponse_MetadataMultiError(errors)
	}

	return nil
}

// GetMovieDetailResponse_MetadataMultiError is an error wrapping multiple
// validation errors returned by GetMovieDetailResponse_Metadata.ValidateAll()
// if the designated constraints aren't met.
type GetMovieDetailResponse_MetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMovieDetailResponse_MetadataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMovieDetailResponse_MetadataMultiError) AllErrors() []error { return m }

// GetMovieDetailResponse_MetadataValidationError is the validation error
// returned by GetMovieDetailResponse_Metadata.Validate if the designated
// constraints aren't met.
type GetMovieDetailResponse_MetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMovieDetailResponse_MetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMovieDetailResponse_MetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMovieDetailResponse_MetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMovieDetailResponse_MetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMovieDetailResponse_MetadataValidationError) ErrorName() string {
	return "GetMovieDetailResponse_MetadataValidationError"
}

// Error satisfies the builtin error interface
func (e GetMovieDetailResponse_MetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMovieDetailResponse_Metadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMovieDetailResponse_MetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMovieDetailResponse_MetadataValidationError{}
